import type { Metadata } from 'next';
import LegalPage from '@/Features/Legal/LegalPage';
import { SUPPORT_EMAIL } from '@/Lib/Constants';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'The terms for using Quiz Dart.',
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <p>
        By using Quiz Dart you agree to these terms. If you do not agree, please
        don&apos;t use the service.
      </p>

      <h2>Your account</h2>
      <p>
        You need a Google account to create quizzes. You&apos;re responsible for
        activity under your account and for keeping your sign-in secure.
      </p>

      <h2>Your content</h2>
      <p>
        You keep ownership of the quizzes and material you create. You grant us a
        license to host, process, and display that content to operate the
        service (including generating questions and images, and showing public
        quizzes in Discover and on leaderboards). You&apos;re responsible for having
        the rights to any material you submit.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit or generate content that is illegal, hateful, harassing, sexually explicit involving minors, or otherwise harmful.</li>
        <li>Infringe others&apos; intellectual property or privacy.</li>
        <li>Abuse, overload, scrape, or attempt to break the service or its rate limits.</li>
        <li>Misuse AI generation to produce disallowed content.</li>
      </ul>
      <p>
        We may remove content and suspend or terminate accounts that violate
        these terms.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Quizzes and images can be generated by AI and may be inaccurate or
        unexpected. Review generated content before relying on or sharing it.
      </p>

      <h2>Credits</h2>
      <p>
        AI generation uses credits that refresh periodically. Credits have no
        cash value and may change over time.
      </p>

      <h2>Service &amp; changes</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; without warranties, to the extent
        permitted by law. We may modify or discontinue features, and may update
        these terms; continued use means you accept the changes.
      </p>

      <h2>Contact</h2>
      <p>
        Questions: <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalPage>
  );
}
